on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test!!
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: action init
        id: test_id
        uses: tsukuba-mas/platex-action@main
        with:
          who-to-greet: "hello, world"
